### ISSUE TITLE
Profile Missing

### ISSUE THREAD

**Issue by DevarajR722** [gtech-mulearn/IEEE-LAUNCHPAD#298]
My profile devarajr@mulearn.md has been created 2 days ago, Now it is missing

**Comment by A6rron** [comment]
Did your pr got merged or closed ?

**Comment by A6rron** [comment]
> My profile devarajr@mulearn.md has been created 2 days ago, Now it is missing

Did your pr got merged or closed?

**Comment by DevarajR722** [comment]
i am not able to find my profile on main

**Comment by A6rron** [comment]
> i am not able to find my profile on main

you need to copy the template.md file and add a file called profile, the steps to do this are in readme file.
